### ISSUE TITLE
Übertragung von Evaluationsparametern zur Evalierung

### ISSUE THREAD

**Issue by alexdobry** [THK-ADV/lwm-reloaded#1]
Als MV möchte man die Parameter am Ende des Praktikums festlegen, anhand derer das Praktikum evaluiert wird.
Diese Parameter gelten als Minimal-Anforderungen.

```
eval : {
  attendance: int,
  certificate: int,
  bonus: int,
  supplement: int
}
```

**Comment by umuesse** [comment]
Die Parameter zur Evaluierung sollten als Ressource definiert werden, sodass das Fehlerpotenzial innerhalb eines Praktikums gering gehalten wird. 
Hierfür werden dann alle CRUD-Funktionalitäten benötigt, wobei ein Delete nicht zwingend erforderlich ist.

**Comment by alexdobry** [comment]
Eigene eigene Ressource soll dazu dienen, diese Eval-Config zu persistieren. Updates sollen auch möglich sein
