### ISSUE TITLE
CREATE schedule: send response in case of conflicts

### ISSUE THREAD

**Issue by umuesse** [THK-ADV/lwm-reloaded#69]
Im Falle von konfliktären Studenten kann es dazu kommen, dass der Versuch, dennoch einen Staffelplan zu erstellen, ins Leere läuft, bzw. kein Ende findet. Dies muss nach einer Zeit abgebrochen und dem Frontend mitgeteilt werden, da sonst das Frontend nicht mehr handlungsfähig ist.

Response sollte sein: 
Student, konfliktäres Praktikum, konfliktärer Termin

**Comment by alexdobry** [comment]
Ein Stackoverflow bei der rekursiven Funktion `randomAvoiding(group)(implicit groups)` hat zu einem "crash" geführt, was aber nur bei einem Deadlock der Gruppen/Studenten auftauchen kann. Das Problem wurde behoben, indem die Rekursion ausschließend dann verwendet wird, wenn ein `random avoiding group` überhaupt möglich ist. Andernfalls wird die aktuelle Gruppe einfach zurückgegeben.
